/* Local generated artwork and original SVG details; CSS owns actor motion. */
'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const svg = (body, box='0 0 100 100') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${box}" aria-hidden="true">${body}</svg>`;
const line = 'stroke="#24212b" stroke-width="2" stroke-linejoin="round"';
const art = {
 toilet: (occupant='Nobody') => svg(`<g class="wing left" fill="#d6d8e4" ${line}><path d="M29 49Q8 49 3 30Q15 42 32 36L38 53Z"/><path d="M5 33l12 12m-6-6 12 10"/></g><g class="wing" fill="#d6d8e4" ${line}><path d="M70 43Q90 49 98 32Q97 53 74 60L64 54Z"/><path d="M94 40l-12 9m11-4-12 9"/></g><path d="M48 15l27 7v29L46 43Z" fill="#d8dbe1" ${line}/><path d="M48 15L37 23v24l10-4V24l28-2" fill="#aaaeba" ${line}/><path d="M37 23l27 8 11-9M64 31v16" fill="none" ${line}/><path d="M50 61l-5 16-15 5 7 8 33-7-16-9 9-16" fill="#c1c5cf" ${line}/><path d="M21 47q14-18 39-1t-2 24q-15 13-32-1Z" fill="#eff0ee" ${line}/><ellipse cx="41" cy="51" rx="24" ry="12" fill="#b9c2d7" ${line}/><ellipse cx="41" cy="52" rx="17" ry="7" fill="#3d53a1"/><path d="M25 53q14-8 31 0" stroke="#9ee4ef" stroke-width="3" fill="none"/><path d="M21 57q19 14 41 0" fill="none" stroke="#fff" stroke-width="4"/>${occupant==='Nobody'?'':occupant==='Cow'?'<ellipse cx="48" cy="36" rx="16" ry="13" fill="#eee" stroke="#333"/><circle cx="42" cy="33" r="6" fill="#222"/><path d="M37 28l-7-8m29 6 8-7" stroke="#eee" stroke-width="5"/>':'<ellipse cx="49" cy="35" rx="12" ry="15" fill="#d79473" stroke="#432f2a"/><circle cx="50" cy="18" r="9" fill="#e6b092" stroke="#432f2a"/><path d="M43 46l-8 15m20-16 6 13" stroke="#d79473" stroke-width="7"/>'}`),
 paper: () => svg('<path d="M20 45l39-12 18 24-39 16Z" fill="#e8e9e5" stroke="#999" stroke-width="3"/><ellipse cx="60" cy="43" rx="14" ry="20" fill="white" stroke="#a8a5aa" stroke-width="3"/><ellipse cx="60" cy="43" rx="5" ry="9" fill="#444"/><path d="M20 45L8 55l30 18 10-8" fill="#c4c5c7" stroke="#999" stroke-width="2"/>'),
 fish: (kind='Mutants') => svg(`<g class="fish-body"><path d="M25 45L3 22l4 52 22-14" fill="${kind==='Skeletons'?'#aaaca5':'#714ea0'}" ${line}/><path d="M20 49Q55 12 90 48Q61 88 20 49" fill="${kind==='Skeletons'?'#545c61':'#39859b'}" ${line}/>${kind==='Skeletons'?'<path d="M25 50h55m-42-9v21m12-29v36m12-37v32m12-26v20" stroke="#e6e5bd" stroke-width="4"/>':'<path d="M35 28l8-16 10 13 12-8 5 13M38 69l7 13 13-12" fill="#90ba4d" stroke="#283321" stroke-width="2"/>'}<circle cx="77" cy="44" r="10" fill="#e0e298" ${line}/><circle cx="80" cy="44" r="4" fill="#b32036"/><path d="M86 55l-10 4 5-10" fill="#fff"/></g>`),
 person: (kind='Human') => kind==='Fish'?art.fish():kind==='Cow'?svg(`<path d="M22 42h48l7 30H20Z" fill="#eee" ${line}/><ellipse cx="44" cy="51" rx="11" ry="9" fill="#25252b"/><path d="M26 67v23m39-23v23" stroke="#eee" stroke-width="10"/><path d="M26 91h-9m48 0h10" stroke="#444" stroke-width="4"/><ellipse cx="49" cy="28" rx="23" ry="19" fill="#eee" ${line}/><path d="M28 20L17 8l2 20m48-8L79 8l-1 20" fill="#c4b49e" ${line}/><ellipse cx="49" cy="37" rx="15" ry="9" fill="#d8aab0"/><circle cx="40" cy="24" r="3"/><circle cx="59" cy="24" r="3"/>`):svg(`<path d="M30 81l-9 15m42-15 14 15" stroke="#d89e7e" stroke-width="10"/><path d="M24 52L8 39m59 13 18-15" stroke="#deb094" stroke-width="9"/><ellipse cx="47" cy="58" rx="24" ry="28" fill="${kind==='Mime'?'#eee':kind==='Slime'?'#8eae39':'#d8a181'}" ${line}/>${kind==='Mime'?'<path d="M25 47h44m-45 9h46m-44 9h43m-39 9h36" stroke="#24242b" stroke-width="5"/>':''}<path d="M28 79h38l-2 9H30Z" fill="#574a7f"/><circle cx="47" cy="24" r="17" fill="${kind==='Mime'?'#eee':kind==='Slime'?'#aecb47':'#e6b495'}" ${line}/><path d="M30 18Q46-1 65 18" fill="${kind==='Mime'?'#19191f':'#513531'}"/><circle cx="41" cy="24" r="2.5"/><circle cx="53" cy="24" r="2.5"/><path d="M40 34q7 5 14-1" fill="none" stroke="#553338" stroke-width="2"/>`),
 lizard: () => svg(`<path d="M44 58Q3 88 9 58Q10 41 23 48Q34 58 19 60" fill="none" stroke="#557e2c" stroke-width="10"/><path d="M26 46Q47 22 75 43L89 51 71 63 32 61Z" fill="#87ad3f" ${line}/><path d="M37 37l8-12 5 8 10-8 4 12" fill="#bfd35e" stroke="#394920"/><path d="M40 58l-8 15 15 2m16-18 9 13 12-1" fill="none" stroke="#77a62d" stroke-width="6"/><circle cx="71" cy="40" r="13" fill="#b6c96d" ${line}/><circle cx="75" cy="38" r="5" fill="#252328"/><path class="tongue" d="M83 52h40l5-6m-5 6 5 6" fill="none" stroke="#d76b8f" stroke-width="3"/><path d="M78 54h13" stroke="#252328" stroke-width="2"/>`,'0 0 130 90'),
 eye: () => svg('<path d="M24 13l6 13M72 13l-5 15M7 53l17 2M80 52l18 5M24 83l9-16M78 85l-10-17" stroke="#381e32" stroke-width="6"/><path d="M25 24Q53 5 78 29L83 65Q52 91 18 66Z" fill="#70263d" stroke="#261e2c" stroke-width="4"/><ellipse cx="50" cy="50" rx="26" ry="34" fill="#e1dcca" stroke="#422333" stroke-width="4"/><ellipse class="iris" cx="50" cy="51" rx="11" ry="22" fill="#af253a"/><ellipse class="iris" cx="50" cy="51" rx="4" ry="16" fill="#111"/><circle cx="46" cy="40" r="5" fill="white"/>'),
 mouth: () => svg('<path d="M4 45Q11 8 50 17Q86 5 97 45Q91 87 51 76Q13 94 4 45" fill="#951c3d" stroke="#241727" stroke-width="5"/><ellipse cx="51" cy="46" rx="39" ry="24" fill="#143b22"/><path d="M19 30l7 23 6-25 8 25 8-26 7 28 8-28 7 26 8-23M20 65l7-23 6 24 8-22 8 23 7-23 8 22 7-23 6 20" fill="#e1ecc2" stroke="#346839" stroke-width="2"/>'),
 cat: () => svg('<path d="M28 67Q4 75 8 38" fill="none" stroke="#a89b78" stroke-width="9"/><ellipse cx="51" cy="64" rx="24" ry="20" fill="#c4b896" stroke="#27262d" stroke-width="2"/><path d="M37 71l-6 19m31-18 9 18" stroke="#c4b896" stroke-width="9"/><path d="M33 42l1-26 17 12 18-12 1 28Q51 64 33 42" fill="#c4b896" stroke="#27262d" stroke-width="2"/><path d="M41 38h6m9 0h6" stroke="#162429" stroke-width="4"/><path d="M51 45l-4-5h8Z" fill="#a3656b"/>'),
 mower: () => svg('<path d="M46 53L30 20H13" fill="none" stroke="#bbb" stroke-width="4"/><path d="M31 53h53l7 24H26Z" fill="#9a3445" stroke="#242328" stroke-width="3"/><rect x="43" y="43" width="28" height="20" rx="4" fill="#777d79" stroke="#29292c" stroke-width="3"/><circle cx="34" cy="77" r="10" fill="#242328" stroke="#9da19a" stroke-width="3"/><circle cx="80" cy="77" r="10" fill="#242328" stroke="#9da19a" stroke-width="3"/>'),
 moon: () => svg('<circle cx="50" cy="50" r="33" fill="#e4d894"/><circle cx="65" cy="40" r="30" fill="#14172c"/>'),
 fractal: () => svg('<path d="M50 4L96 87H4Z M50 87L27 46h46Z M27 46L15 67h24Z M73 46L61 67h24Z" fill="#583195" stroke="#a6efda" stroke-width="2"/>')
};
// One transparent atlas, clipped to its 4 × 4 grid without resampling the artwork.
const sprite=(col,row,extra='')=>`<svg class="painted-art ${extra}" xmlns="http://www.w3.org/2000/svg" viewBox="${col*320} ${row*320} 320 320" aria-hidden="true"><image href="assets/twisted-sprites.png" width="1280" height="1280"/></svg>`;
const skeletonFish=art.fish;
Object.assign(art,{
 toilet:(occupant='Nobody')=>`<span class="porcelain">${sprite(0,0)}${occupant==='Nobody'?'':`<span class="rider">${occupant==='Cow'?sprite(3,3):sprite(0,1)}</span>`}</span>`,
 paper:()=>sprite(1,3),fish:(kind='Mutants')=>kind==='Skeletons'?skeletonFish(kind):sprite(1,0,'fish-body'),
 person:(kind='Human')=>kind==='Fish'?art.fish():kind==='Cow'?sprite(3,3):kind==='Mime'?sprite(1,1):kind==='Slime'?sprite(2,1):sprite(0,1),
 lizard:()=>sprite(2,0),cat:()=>sprite(3,0),mower:()=>sprite(3,1),eye:()=>sprite(0,2),mouth:()=>sprite(1,2),nose:()=>sprite(2,2),skull:()=>sprite(3,2),chimp:()=>sprite(0,3),moon:()=>sprite(2,3)
});
const modules = [
 {id:'bungee',name:'Bungee Roulette',icon:'person',label:'Jumper',choices:['Human','Fish','Cow'],description:'Gravity works. The equipment is questionable.',note:'Jumpers bounce on elastic ropes; some take the express route down. Recreated animation.'},
 {id:'chameleon',name:'Chameleon',icon:'lizard',label:'Company',choices:['Solo wanderers','Conga line'],description:'A colorful little desktop infestation.',note:'Color-shifting creatures, darting tongues, and disappearing desktop scraps. Simplified recreation.'},
 {id:'coming',name:'Coming Soon!',icon:'person',label:'Pitch',choices:['Automatic','Pocket black hole','Self-mowing carpet','Instant vacation'],description:'Products nobody asked for. Prices nobody understands.',note:'An animated presenter and invented novelty ads. The original dialogue is not included.'},
 {id:'toilets',name:'Flying Toilets',icon:'toilet',label:'Occupant',choices:['Nobody','Human','Cow'],description:'Porcelain takes flight. Please remain seated.',note:'Winged porcelain and tumbling paper, drifting through the void. New illustrations inspired by the classic.'},
 {id:'franken',name:'FrankenScreen',icon:'eye',label:'Complexion',choices:['Purple','Sickly green','Crimson'],description:'Some assembly required. Beauty sold separately.',note:'Floating eyes, a nose, stitches, and a toothy mouth on textured skin. Recreated artwork.'},
 {id:'message',name:'Message Mayhem',icon:'person',label:'Surface',choices:['Bathroom tiles','Chalkboard'],description:'Leave a message. Make a little mess.',note:'A wandering writer reveals your message. These two treatments are new recreations.'},
 {id:'mike',name:"Mike’s So-called Life",icon:'person',label:'Room',choices:['Living room','Late-night TV','Kitchen'],description:'Another big day of absolutely nothing.',note:'A little room drifts around the screen while Mike takes it easy. Simplified domestic scene.'},
 {id:'mime',name:'Mime Hunt',icon:'person',label:'Weapon',choices:['Paintballs','Tomatoes','Ray gun'],description:'Silence is golden. So is good aim.',note:'Tap the mimes to score, or watch the automatic aim. Three new effect variations.'},
 {id:'boris',name:"Mowin’ Boris",icon:'cat',label:'Driver',choices:['Mowin’ man','Boris gets revenge'],description:'An ordinary day in a very unusual garden.',note:'A mower, leaping cats, and a driver reversal. Cartoon near-misses replace the original gore.'},
 {id:'phlegm',name:'Phlegm Boy',icon:'person',label:'Goo',choices:['Slime green','Radioactive','Bubblegum'],description:'Your screen needed cleaning anyway.',note:'An elastic little creature leaves dripping splats. New goo and synthesized sound effects.'},
 {id:'clocks',name:'Shock Clocks',icon:'eye',label:'Timekeeper',choices:['Rotting head','Clockwork chimp','Overcoat'],description:'Have you got the time? Unfortunately, yes.',note:'Three strange clock faces showing your actual local time. Recreated designs.'},
 {id:'swamp',name:'Toxic Swamp',icon:'fish',label:'Wildlife',choices:['Mutants','Skeletons','Mixed'],description:'Life finds a way. Even here.',note:'Mutant fish, bubbles, weeds, and a slow descent to the bottom. Simplified recreation.'},
 {id:'voyeur',name:'Voyeur',icon:'moon',label:'Neighborhood',choices:['Night owls','Restless city','Visitors'],description:'The neighbors are up to something.',note:'Lit apartment windows, silhouettes, and a distant city. New miniature scenes; original story branches are not reproduced.'},
 {id:'mandelbrot',name:'Mandelbrot',icon:'fractal',label:'Palette',choices:['Electric violet','Ocean','Ember'],description:'A small equation. An enormous place.',note:'An actual escape-time Mandelbrot set with a slow breathing zoom. Extra fractal collection.',fractal:true},
 {id:'julia',name:'Julia Drift',icon:'fractal',label:'Palette',choices:['Electric violet','Ocean','Ember'],description:'Watch a mathematical world change its mind.',note:'A Julia set with a slowly changing complex parameter. Extra fractal collection.',fractal:true},
 {id:'forest',name:'Fractal Forest',icon:'fractal',label:'Season',choices:['Moonlight','Spring','Autumn'],description:'Every branch holds a smaller forest.',note:'Recursive branching geometry that grows and gently moves. Extra fractal collection.',fractal:true},
 {id:'kaleido',name:'Fractal Kaleidoscope',icon:'fractal',label:'Palette',choices:['Electric violet','Ocean','Ember'],description:'Little triangles, all the way down.',note:'Recursive Sierpiński geometry with sixfold rotation. Extra fractal collection.',fractal:true}
];
let saved={};try{saved=JSON.parse(localStorage.getItem('twisted.v1')||'{}')}catch{}
const state={id:modules.some(m=>m.id===saved.id)?saved.id:'toilets',speed:Math.min(2,Math.max(.25,Number(saved.speed)||1)),density:Math.min(12,Math.max(2,Number(saved.density)||6)),variants:saved.variants&&typeof saved.variants==='object'?saved.variants:{},message:typeof saved.message==='string'?saved.message.slice(0,48):'TAKE A BREAK',paused:false,sound:false,shuffle:false,interval:60,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,elapsed:0,sceneTime:0,score:0,saving:false};
const persist=()=>{try{localStorage.setItem('twisted.v1',JSON.stringify({id:state.id,speed:state.speed,density:state.density,variants:state.variants,message:state.message}))}catch{}};
const current=()=>modules.find(m=>m.id===state.id);
const variant=()=>current().choices.includes(state.variants[state.id])?state.variants[state.id]:current().choices[0];
let seed=42;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
const num=(a,b)=>a+random()*(b-a);
const vars=o=>Object.entries(o).map(([k,v])=>`--${k}:${v}`).join(';');
const actor=(cls,html,style='')=>`<div class="actor ${cls}" style="${style}">${html}</div>`;
function list(){const group=Boolean(current().fractal);$('collection').value=group?'fractals':'twisted';$('moduleList').innerHTML=modules.filter(m=>Boolean(m.fractal)===group).map((m,i)=>`<button class="module-item" data-module="${m.id}" aria-current="${m.id===state.id}">${art[m.icon]()}<span>${esc(m.name)}</span><span class="number">${String(i+1).padStart(2,'0')}</span></button>`).join('')}
function settings(){const m=current();$('variantLabel').textContent=m.label;$('variant').innerHTML=m.choices.map(x=>`<option${x===variant()?' selected':''}>${esc(x)}</option>`).join('');$('speed').value=state.speed;$('speedValue').textContent=state.speed+'×';$('density').value=state.density;$('densityValue').textContent=state.density;const densityLabel=document.querySelector('label[for=density]');densityLabel.firstChild.textContent=m.fractal?'Detail ':m.id==='franken'?'Stitches ':'Population ';densityLabel.hidden=$('density').hidden=['coming','message','mike','clocks','voyeur'].includes(m.id);$('messageRow').hidden=m.id!=='message';$('message').value=state.message;$('previewTitle').textContent=m.name;$('description').textContent=m.description;$('sceneNote').textContent=m.note;$('moduleIcon').innerHTML=art[m.icon]();$('motionButton').textContent='Reduced motion: '+(state.reduced?'on':'off');$('motionButton').setAttribute('aria-pressed',state.reduced);document.documentElement.style.setProperty('--speed',state.speed*(state.reduced?.25:1));}
function select(id){if(!modules.some(m=>m.id===id))return;state.id=id;state.sceneTime=0;state.elapsed=0;state.score=0;list();settings();render();persist()}
function scale(){const r=$('screen').getBoundingClientRect();$('world').style.setProperty('--scale',Math.min(r.width/640,r.height/480))}
function render(){seed=42;const w=$('world'),v=variant(),n=state.density;w.className='';w.style.filter='';let html='';
 switch(state.id){
 case 'toilets':
  w.className='upstream-toilets';
  for(let i=0;i<n*3+8;i++){const paper=i%4===2;const speed=paper?'tst'+(i%3+1):'t'+(i%3+1);html+=`<div class="${paper?'toast':'toaster'} ${speed} p${6+i%28}" style="animation-delay:-${(i*1.13)%8}s">${paper?art.paper():art.toilet(v)}</div>`}break;
 case 'bungee':
  for(let i=0;i<n;i++)html+=`<div class="bungee ${i%3===0?'breaking':''}" style="left:${35+i*550/n}px;${vars({duration:num(7,12)+'s',delay:-num(0,10)+'s'})}">${art.person(v)}</div>`;html+='<div class="floor-line"></div>';break;
 case 'chameleon':
  for(let i=0;i<n;i++){html+=actor('lizard',art.lizard(),vars({y:(v==='Conga line'?210:60+i*340/n)+'px',duration:v==='Conga line'?'24s':num(14,25)+'s',delay:-(i*3.6)+'s'}));html+=`<div class="desktop-file" style="${vars({x:num(70,550)+'px',y:num(60,390)+'px',delay:-num(0,16)+'s'})}"></div>`}break;
 case 'coming':html=`<div class="stage-curtain"></div><div class="advert"><small>COMING SOON TO A DESKTOP NEAR YOU</small><h3 id="adName"></h3><p id="adPitch"></p><small>ABSOLUTELY UNNECESSARY. ENTIRELY ESSENTIAL.</small></div><div class="presenter">${art.person()}</div>`;break;
 case 'franken':w.className='franken';w.style.filter=v==='Sickly green'?'hue-rotate(170deg)':v==='Crimson'?'hue-rotate(80deg)':'';html=`<div class="eye left-eye">${art.eye()}</div><div class="eye right-eye">${art.eye()}</div><div class="nose">${art.nose()}</div><div class="mouth">${art.mouth()}</div>`;for(let i=0;i<n*2;i++)html+=`<div class="stitch" style="${vars({x:num(0,560)+'px',y:num(0,470)+'px',angle:num(-65,65)+'deg'})}"></div>`;break;
 case 'message':w.className='message-scene'+(v==='Chalkboard'?' chalk':'');html=`<div class="graffiti">${esc(state.message||'TAKE A BREAK')}</div><div class="writer">${art.person()}</div>`;break;
 case 'mike':html=`<div class="trailer"><div class="room-picture"></div><div class="room-floor"></div><div class="sofa" style="${v==='Kitchen'?'border-radius:0;background:#bbc6ae;height:90px;width:100px':''}"></div><div class="tv" style="${v==='Late-night TV'?'box-shadow:0 0 55px 18px #73a8c966':v==='Kitchen'?'height:125px;top:40px;background:#cbcdbb':''}"></div><div class="mike">${art.person()}</div></div>`;break;
 case 'mime':html='<div class="score" id="score">MIME HUNT · 0 HITS</div><div class="crosshair"></div>';for(let i=0;i<n;i++)html+=`<button class="actor mime" aria-label="Hit mime ${i+1}" style="${vars({y:60+i*330/n+'px',duration:num(11,21)+'s',delay:-num(0,17)+'s'})}">${art.person('Mime')}</button>`;break;
 case 'boris':html='<div class="meadow"></div>';for(let i=0;i<n;i++)html+=`<div class="cat" style="${vars({x:num(30,570)+'px',y:num(18,60)+'px',duration:num(4,9)+'s',delay:-num(0,6)+'s'})}">${v==='Boris gets revenge'?art.person():art.cat()}</div>`;html+=`<div class="mower"><div style="position:absolute;left:0;top:0;width:65px;height:80px">${v==='Boris gets revenge'?art.cat():art.person()}</div><div style="position:absolute;left:48px;top:15px;width:90px;height:80px">${art.mower()}</div></div>`;break;
 case 'phlegm':w.style.filter=v==='Bubblegum'?'hue-rotate(230deg)':v==='Radioactive'?'hue-rotate(40deg) saturate(2)':'';for(let i=0;i<n*3;i++)html+=`<div class="gunk-dot" style="${vars({x:num(20,600)+'px',y:num(0,360)+'px',size:num(14,58)+'px',duration:num(6,14)+'s',delay:-num(0,13)+'s'})}"></div>`;html+=`<div class="slime-boy">${art.person('Slime')}</div>`;break;
 case 'clocks':html=`<div class="clock-creature">${v==='Rotting head'?art.skull():v==='Clockwork chimp'?art.chimp():art.person()}<div class="clock-display"><time id="sceneClock"></time><small id="sceneDate"></small></div></div>`;break;
 case 'swamp':w.className='upstream-swamp';for(let i=0;i<n+3;i++){const kind=v==='Mixed'?(i%2?'Mutants':'Skeletons'):v;html+=`<div class="fish row${1+i%9} ${i%2?'rtl':'ltr'}" style="animation-delay:-${i*2.4}s;width:${num(72,118)}px;height:100px">${art.fish(kind)}</div>`;}html+='<b class="bubbles"></b><div class="swamp-floor"></div>';for(let i=0;i<12;i++)html+=`<div class="weed" style="left:${num(0,640)}px;height:${num(35,95)}px;animation-delay:${-num(0,4)}s"></div>`;html+=`<div class="sinker">${art.person()}<div style="height:13px;background:#70766b;width:50px;margin-top:-15px"></div></div>`;break;
 case 'voyeur':w.className='night';for(let i=0;i<35;i++)html+=`<i class="star" style="${vars({x:num(0,640)+'px',y:num(0,250)+'px',duration:num(2,5)+'s'})}"></i>`;html+='<div class="skyline">'+Array.from({length:14},()=>`<i style="--h:${num(40,220)}px"></i>`).join('')+'</div><div class="building">';for(let i=0;i<16;i++)html+=`<div class="room-window" style="${vars({duration:(v==='Restless city'?7:19)+'s',delay:-num(0,20)+'s'})}"><div class="silhouette" style="${vars({duration:num(3,8)+'s',delay:-num(0,7)+'s'})}">${i%4===0?art.cat():art.person()}</div></div>`;html+='</div>';if(v==='Visitors')html+='<div class="ufo"></div>';break;
 default:html='<canvas class="fractal-canvas" width="320" height="240" aria-label="Mathematically generated fractal"></canvas><span class="fractal-label">'+esc(current().name).toUpperCase()+'</span>';
 }
 w.innerHTML=html;state.sceneTime=0;fractalCache=null;updateClock();updateAd();scale();
}
const ads=[['Pocket black hole','Everything you own. Now conveniently nowhere.'],['Self-mowing carpet','The living room that trims itself.'],['Instant vacation','Three seconds of paradise. Batteries not included.']];
function updateAd(){if(state.id!=='coming')return;const idx=variant()==='Automatic'?Math.floor(state.sceneTime/9)%3:current().choices.indexOf(variant())-1;$('adName').textContent=ads[idx][0].toUpperCase();$('adPitch').textContent=ads[idx][1]}
function updateClock(){const now=new Date();$('menuClock').textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if($('sceneClock')){$('sceneClock').textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});$('sceneDate').textContent=now.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}}
let audioContext=null;const activeSounds=new Set();
function tone(freq=180,duration=.12){if(!state.sound||state.paused||document.hidden)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=state.id==='phlegm'?'sawtooth':'sine';o.frequency.setValueAtTime(freq,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.4),audioContext.currentTime+duration);g.gain.setValueAtTime(.035,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g);g.connect(audioContext.destination);activeSounds.add(o);o.onended=()=>{o.disconnect();g.disconnect();activeSounds.delete(o)};o.start();o.stop(audioContext.currentTime+duration)}catch{state.sound=false;$('sound').checked=false}}
function stopSound(){for(const o of activeSounds){try{o.stop()}catch{}}}
function hit(target,manual=false){if(!target||target.classList.contains('hit')||state.paused)return;target.classList.add('hit');state.score++;$('score').textContent=`MIME HUNT · ${state.score} HITS`;const b=document.createElement('div');b.className='hit-burst';const wr=$('world').getBoundingClientRect(),r=target.getBoundingClientRect(),s=wr.width/640;b.style.left=(r.left-wr.left)/s+'px';b.style.top=(r.top-wr.top)/s+'px';b.style.borderColor=variant()==='Tomatoes'?'#e63739':variant()==='Ray gun'?'#8affe3':'#f8d74e';$('world').appendChild(b);b.addEventListener('animationend',()=>b.remove(),{once:true});tone(manual?500:250);setTimeout(()=>{if(target.isConnected)target.classList.remove('hit')},1500)}
let fractalCache=null,lastDraw=0;
function palette(n,t){const p=variant(),base=p==='Ocean'?170:p==='Ember'?10:265;const hue=(base+n*6+t*8)%360;const s=.8,l=.47;const a=s*Math.min(l,1-l);const f=k=>{const x=(k+hue/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(x-3,9-x,1))))};return[f(0),f(8),f(4)]}
function drawFractal(t){const canvas=$('world').querySelector('canvas');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;
 if(state.id==='mandelbrot'||state.id==='julia'){
  const width=220,height=165;if(canvas.width!==width){canvas.width=width;canvas.height=height}const max=42+state.density*5;const frame=ctx.createImageData(width,height);const zoom=state.id==='mandelbrot'?1+.28*Math.sin(t*.12):1;const cx=-.745+.04*Math.cos(t*.13),cy=.19+.04*Math.sin(t*.1);const colors=Array.from({length:max+1},(_,i)=>palette(i,t));
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){let zx=(x/width-.5)*3.4/zoom,zy=(y/height-.5)*2.55/zoom;let cr=cx,ci=cy;if(state.id==='mandelbrot'){cr=zx-.5;ci=zy;zx=0;zy=0}let i=0;for(;i<max&&zx*zx+zy*zy<4;i++){const xx=zx*zx-zy*zy+cr;zy=2*zx*zy+ci;zx=xx}const idx=(y*width+x)*4;const col=i===max?[3,3,13]:colors[i];frame.data[idx]=col[0];frame.data[idx+1]=col[1];frame.data[idx+2]=col[2];frame.data[idx+3]=255}ctx.putImageData(frame,0,0);fractalCache=true;
 }else{
  if(canvas.width!==640){canvas.width=640;canvas.height=480}ctx.fillStyle='#040610';ctx.fillRect(0,0,640,480);
  if(state.id==='forest'){const base=variant()==='Spring'?112:variant()==='Autumn'?24:185;const depth=Math.min(10,5+Math.floor(state.density/2));function branch(x,y,len,angle,d){if(d===0)return;const bend=Math.sin(t*.3+d*.3)*.065;const ex=x+Math.cos(angle)*len,ey=y+Math.sin(angle)*len;ctx.strokeStyle=`hsl(${base+d*3} 48% ${75-d*4}%)`;ctx.lineWidth=Math.max(.5,d*.75);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(ex,ey);ctx.stroke();branch(ex,ey,len*.73,angle-.43+bend,d-1);branch(ex,ey,len*.73,angle+.43+bend,d-1)}branch(320,465,103,-Math.PI/2,depth)}
  else{const depth=Math.min(6,2+Math.floor(state.density/3));ctx.save();ctx.translate(320,240);ctx.rotate(t*.07);function triangle(x,y,size,d){if(d===0){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+size,y);ctx.lineTo(x+size/2,y-size*.866);ctx.closePath();ctx.stroke();return}triangle(x,y,size/2,d-1);triangle(x+size/2,y,size/2,d-1);triangle(x+size/4,y-size*.433,size/2,d-1)}for(let i=0;i<6;i++){ctx.rotate(Math.PI/3);const col=palette(i*9,t);ctx.strokeStyle=`rgb(${col})`;ctx.lineWidth=.8;triangle(0,0,225*(1+.1*Math.sin(t*.3)),depth)}ctx.restore()}fractalCache=true;
 }
}
let previous=performance.now(),lastEvent=0,lastClock=0;
function tick(now){const dt=Math.min((now-previous)/1000,.1);previous=now;if(!state.paused&&!document.hidden){state.sceneTime+=dt*state.speed*(state.reduced?.25:1);state.elapsed+=dt;if(current().fractal&&now-lastDraw>(state.reduced?500:120)){drawFractal(state.sceneTime);lastDraw=now}if(now-lastEvent>3000){lastEvent=now;updateAd();if(state.id==='mime'){const targets=[...document.querySelectorAll('.mime:not(.hit)')].filter(el=>{const r=el.getBoundingClientRect(),p=$('screen').getBoundingClientRect();return r.left>p.left&&r.right<p.right});hit(targets[Math.floor(Math.random()*targets.length)])}else if(['swamp','phlegm','bungee','toilets'].includes(state.id))tone(state.id==='phlegm'?100:160,.15)}if(state.shuffle&&state.elapsed>=state.interval)next(true)}if(now-lastClock>1000){updateClock();lastClock=now}requestAnimationFrame(tick)}
function pause(){state.paused=!state.paused;document.body.classList.toggle('paused',state.paused||document.hidden);$('pause').textContent=state.paused?'Resume':'Pause';$('status').textContent=state.paused?'Preview paused':'Preview running';if(state.paused)stopSound()}
function next(shuffle=false){const set=modules.filter(m=>Boolean(m.fractal)===Boolean(current().fractal));const i=set.findIndex(m=>m.id===state.id);select(set[(i+(shuffle?1+Math.floor(Math.random()*(set.length-1)):1))%set.length].id)}
let wakeLock=null,hideTimer=null;
async function requestWake(){if(state.saving&&!document.hidden&&navigator.wakeLock){try{wakeLock=await navigator.wakeLock.request('screen')}catch{}}}
function showControls(){if(!state.saving)return;$('screen').classList.add('show-controls');clearTimeout(hideTimer);hideTimer=setTimeout(()=>$('screen').classList.remove('show-controls'),3000)}
async function startSaver(){state.saving=true;document.body.classList.add('saving');$('exitSaver').hidden=false;$('saverHint').hidden=false;if(state.paused)pause();scale();showControls();$('exitSaver').focus({preventScroll:true});requestWake();try{if($('screen').requestFullscreen)await $('screen').requestFullscreen()}catch{}scale()}
async function exitSaver(){state.saving=false;document.body.classList.remove('saving');$('exitSaver').hidden=true;$('saverHint').hidden=true;clearTimeout(hideTimer);if(wakeLock){await wakeLock.release().catch(()=>{});wakeLock=null}if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});scale();$('start').focus({preventScroll:true})}
$('moduleList').addEventListener('click',e=>{const b=e.target.closest('[data-module]');if(b)select(b.dataset.module)});
$('collection').addEventListener('change',()=>select($('collection').value==='fractals'?'mandelbrot':'toilets'));
$('variant').addEventListener('change',()=>{state.variants[state.id]=$('variant').value;render();persist()});
$('speed').addEventListener('input',()=>{state.speed=Number($('speed').value);settings();persist()});
$('density').addEventListener('input',()=>{state.density=Number($('density').value);settings();render();persist()});
$('message').addEventListener('input',()=>{state.message=$('message').value;const text=$('world').querySelector('.graffiti');if(text)text.textContent=state.message||'TAKE A BREAK';persist()});
$('pause').addEventListener('click',pause);$('next').addEventListener('click',()=>next());$('restart').addEventListener('click',()=>{state.score=0;render()});
$('sound').addEventListener('change',()=>{state.sound=$('sound').checked;if(state.sound)tone(440);else stopSound()});
$('shuffle').addEventListener('change',()=>{state.shuffle=$('shuffle').checked;state.elapsed=0});$('interval').addEventListener('change',()=>{state.interval=Number($('interval').value);state.elapsed=0});
$('motionButton').addEventListener('click',()=>{state.reduced=!state.reduced;settings()});
$('start').addEventListener('click',startSaver);$('exitSaver').addEventListener('click',exitSaver);
$('screen').addEventListener('pointermove',showControls);$('screen').addEventListener('pointerdown',showControls);
$('world').addEventListener('click',e=>{const target=e.target.closest('.mime');if(target)hit(target,true)});
$('aboutButton').addEventListener('click',()=>{$('about').showModal()});$('closeAbout').addEventListener('click',()=>$('about').close());
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.saving){exitSaver();return}if(e.target.closest(state.saving?'input,select,dialog':'input,select,button,dialog'))return;if(e.code==='Space'){e.preventDefault();pause()}else if(e.key.toLowerCase()==='n')next();else if(e.key.toLowerCase()==='f')startSaver()});
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&state.saving)exitSaver();scale()});
document.addEventListener('visibilitychange',()=>{document.body.classList.toggle('paused',state.paused||document.hidden);if(document.hidden)stopSound();else requestWake()});
window.addEventListener('pagehide',()=>{stopSound();if(wakeLock)wakeLock.release().catch(()=>{})});
new ResizeObserver(scale).observe($('screen'));window.addEventListener('resize',scale);
select(state.id);requestAnimationFrame(tick);
